### PR TITLE
Update webpack config file.

### PR DESCRIPTION
**Pull request by lesykos**
- Set a variables for entry & output path;
- Custom output filename for main .js file;
- Remove modulesDirectories (duplicate with default value);
- devServer: remove duplicated config, add historyApiFallback;
- Change path and name for .css file;

### CODE REVIEW

**Comment by moarwick** [comment]
@Lesuk I just realized that after your PR, with assets getting saved into the `static/` subfolder, now when we run `npm run build` and attempt to run the compiled project project from the `/dist` folder, it's broken (bad file paths). I tried a few things, and my latest version sort of works, but relies on a bunch of `mv` commands in the build script to move the font files.. ugly. Any chance you can pull latest and have a look? Hitting my Webpack know-how limits.. Thanks!

**Comment by lesykos** [comment]
@moarwick, sadly to hear this. It's just a problem with fonts?

**Comment by moarwick** [comment]
yes. the fonts get built into the `dist/` root, but the paths are expecting them to be in `dist/static/css/`. i couldn't find a way to adjust webpack config to copy them to the correct location, so currently the NPM `build` script moves them over. feels hacky, plus the `mv` command does not work on Windows :(  let me know if you have any ideas, otherwise I think I will revert to the old folder structure..

**Comment by lesykos** [comment]
In this situation, IMO you should return to the old folder structure. I didn't think about fonts when doing this.

**Pull request merged**
